<a href="https://colab.research.google.com/github/HoaiNam2k5/Deep_Learning_Practice/blob/main/Lab1_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0

In [1]:
import tensorflow as tf
tensor_1 = tf.zeros([2, 3])
print(tensor_1)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


### 2. Cho X = [[1, 2, 3], [4, 5, 6]], tạo tensor có kích thước và dtype như X với các phần tử gán 0

In [2]:
X = [[1, 2, 3], [4, 5, 6]]
tensor_2 = tf.zeros_like(X)
print(tensor_2)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


### 3. Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5

In [3]:
tensor_3 = tf.fill([3, 2], 5)
print(tensor_3)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


### 4. Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]

In [4]:
# Vì chỉ có 3 số chẵn trong [5, 10] là 6, 8, 10, ta tạo 50 phần tử bằng cách lặp lại hoặc linspace
tensor_4 = tf.linspace(6.0, 10.0, 50)
print(tensor_4)

tf.Tensor(
[ 6.         6.0816326  6.163265   6.244898   6.3265305  6.408163
  6.4897957  6.5714283  6.6530614  6.734694   6.8163266  6.897959
  6.979592   7.0612245  7.142857   7.2244897  7.3061223  7.387755
  7.469388   7.5510206  7.632653   7.714286   7.7959185  7.877551
  7.9591837  8.040816   8.122449   8.204082   8.285714   8.367347
  8.448979   8.530612   8.612245   8.693877   8.77551    8.857142
  8.938776   9.020409   9.102041   9.183674   9.265306   9.346939
  9.428572   9.510204   9.591837   9.67347    9.755102   9.836735
  9.918367  10.       ], shape=(50,), dtype=float32)


### 5. Tạo một tensor 1-chiều có giá trị như [10, 12, 14, …, 100]

In [5]:
tensor_5 = tf.range(start=10, limit=101, delta=2)
print(tensor_5)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


### 6. Tạo một tensor [3, 2] ngẫu nhiên theo phân phối normal (mean=0, std=2)

In [6]:
tensor_6 = tf.random.normal(shape=[3, 2], mean=0.0, stddev=2.0)
print(tensor_6)

tf.Tensor(
[[-1.7600176  -0.9398406 ]
 [-0.17777295 -0.5276406 ]
 [-2.403424   -1.789363  ]], shape=(3, 2), dtype=float32)


### 7. Tạo một tensor [3, 2] ngẫu nhiên theo phân phối uniform trong [0, 2]

In [7]:
tensor_7 = tf.random.uniform(shape=[3, 2], minval=0, maxval=2)
print(tensor_7)

tf.Tensor(
[[0.4571283  0.23752356]
 [0.09196758 0.95381093]
 [0.6707728  1.8755212 ]], shape=(3, 2), dtype=float32)


### 8. Shuffle tensor X = [[1, 2], [3, 4], [5, 6]] theo chiều thứ nhất

In [8]:
X_8 = tf.constant([[1, 2], [3, 4], [5, 6]])
tensor_8 = tf.random.shuffle(X_8)
print(tensor_8)

tf.Tensor(
[[5 6]
 [3 4]
 [1 2]], shape=(3, 2), dtype=int32)


### 9. Hãy tạo ngẫu nhiên tensor kích thước (10, 10, 3). Cắt thành tensor có kích thước (5, 5, 3) (sử dụng random_crop)

In [9]:
# Tạo tensor ngẫu nhiên kích thước (10, 10, 3)
tensor_9 = tf.random.uniform(shape=[10, 10, 3], minval=0, maxval=255)
# Thực hiện cắt ngẫu nhiên xuống kích thước (5, 5, 3)
cropped_tensor_9 = tf.image.random_crop(tensor_9, size=[5, 5, 3])
print("Kích thước sau khi crop:", cropped_tensor_9.shape)
print(cropped_tensor_9)

Kích thước sau khi crop: (5, 5, 3)
tf.Tensor(
[[[194.93358   35.64838  153.56664 ]
  [ 87.84743  224.06203  103.08953 ]
  [ 88.74418  163.68333  142.20901 ]
  [ 58.740955 101.57931  186.8881  ]
  [153.34639  200.98283  169.9244  ]]

 [[136.81467  217.35196  214.60612 ]
  [111.20614   73.571106   5.511133]
  [128.16895  131.28897   17.86965 ]
  [149.85004  145.46587  228.97478 ]
  [ 63.352055 237.2517    91.31087 ]]

 [[154.1946   105.82773  145.44087 ]
  [188.1967   115.01983  121.054665]
  [ 38.903893  55.523197 241.17877 ]
  [ 62.22911  234.19897   82.07438 ]
  [177.76318  174.76414  101.16632 ]]

 [[206.48868  155.13185  145.31581 ]
  [170.06812  226.04514  226.25545 ]
  [210.41885  126.277374 227.52188 ]
  [243.55075   69.54402  137.25037 ]
  [ 67.691635 103.30116  155.09662 ]]

 [[ 40.111652 233.11624   16.185156]
  [ 24.662804 175.61014  153.03535 ]
  [184.46165   66.66736   54.46278 ]
  [202.60263   57.24171   62.57659 ]
  [217.32988  191.89018    4.001216]]], shape=(5, 5, 3), d

### 10. Tạo ngẫu nhiên hai tensor 1-chiều x, y có 5 phần tử. Trả về x + y nếu x < y, và x – y nếu x > y

In [10]:
x = tf.random.uniform(shape=[5], minval=0, maxval=10)
y = tf.random.uniform(shape=[5], minval=0, maxval=10)

# Sử dụng tf.where để thực hiện logic điều kiện theo từng phần tử
result_10 = tf.where(x < y, x + y, x - y)

print("x:", x.numpy())
print("y:", y.numpy())
print("Kết quả:", result_10.numpy())

x: [5.547947  1.2834406 4.7118783 0.7247317 4.0396547]
y: [0.85416317 4.2537475  2.7774072  2.2881603  5.911607  ]
Kết quả: [4.6937838 5.537188  1.9344711 3.012892  9.9512615]


### 11. Tạo ngẫu nhiên 2 tensor x = (3, 2) [5, 10], y = (2, 3) [15, 20]. Giữ giá trị đường chéo của x và thực hiện x + y.

In [11]:
# Lưu ý: x + y chỉ thực hiện được khi hai ma trận có cùng kích thước hoặc có thể broadcast.
# Đề bài yêu cầu x(3,2) và y(2,3), có lẽ ý bạn là nhân ma trận hoặc cộng sau khi chuyển vị.
x_11 = tf.random.uniform(shape=[3, 2], minval=5, maxval=10)
y_11 = tf.random.uniform(shape=[2, 3], minval=15, maxval=20)

# Giả sử thực hiện x + y_transpose để cùng kích thước (3, 2)
y_t = tf.transpose(y_11)
result_add = x_11 + y_t

print("x_11:\n", x_11.numpy())
print("y_transpose:\n", y_t.numpy())
print("Kết quả cộng:\n", result_add.numpy())

x_11:
 [[7.686226  5.4266872]
 [7.939502  7.608121 ]
 [8.351024  5.4009476]]
y_transpose:
 [[18.177732 19.20373 ]
 [18.244402 18.046736]
 [19.656631 18.285994]]
Kết quả cộng:
 [[25.863958 24.630417]
 [26.183903 25.654858]
 [28.007656 23.686941]]


### 12. Viết hàm tạo 2 tensor ngẫu nhiên kích thước (3, 2, 2) và các hàm cộng, trừ, nhân, chia trong graph

In [12]:
@tf.function
def tensor_operations(x, y):
    add_res = tf.add(x, y)
    sub_res = tf.subtract(x, y)
    mul_res = tf.multiply(x, y)
    div_res = tf.divide(x, y)
    return add_res, sub_res, mul_res, div_res

x_12 = tf.random.uniform(shape=[3, 2, 2])
y_12 = tf.random.uniform(shape=[3, 2, 2])

# Thực thi hàm trong graph
a, s, m, d = tensor_operations(x_12, y_12)
print("Kết quả cộng (3, 2, 2):\n", a.numpy())

Kết quả cộng (3, 2, 2):
 [[[0.8521775  0.8261688 ]
  [1.503468   1.0687076 ]]

 [[0.53948855 0.9800093 ]
  [1.3148291  0.9527484 ]]

 [[1.5158725  0.24035156]
  [0.2513585  1.3675251 ]]]


### 13. Xây dựng model để tính tổng hai tensor x, y

In [13]:
class AddModel(tf.Module):
    @tf.function
    def __call__(self, x, y):
        return x + y

model_add = AddModel()
result_13 = model_add(x_12, y_12)
print("Tổng x + y qua model:", result_13.shape)

Tổng x + y qua model: (3, 2, 2)


### 14. Xây dựng model để tính hiệu và tích hai tensor x, y

In [14]:
class MathModel(tf.Module):
    @tf.function
    def compute(self, x, y):
        diff = x - y
        prod = x * y
        return diff, prod

model_math = MathModel()
diff, prod = model_math.compute(x_12, y_12)
print("Hiệu:", diff.shape, "Tích:", prod.shape)

Hiệu: (3, 2, 2) Tích: (3, 2, 2)


### 15. Xây dựng model để tính chu vi hình chữ nhật P = (a + b) * 2

In [15]:
class PerimeterModel(tf.Module):
    @tf.function
    def calculate(self, a, b):
        return (a + b) * 2

# Giả sử a, b là chiều dài và rộng
a = tf.constant([10.0, 20.0])
b = tf.constant([5.0, 15.0])
model_p = PerimeterModel()
p = model_p.calculate(a, b)
print("Chu vi hình chữ nhật:", p.numpy())

Chu vi hình chữ nhật: [30. 70.]
